### ISSUE TITLE
How to create the mask_folder?

### ISSUE THREAD

**Issue by Mtorriente** [EricArazo/ExemplarCNN#1]
Good Morning,
I am trying to run the code. But when running the 'create_surrogate_data_STL.py', it appears an error. I think is because i haven´t create the mask folder but i don´t know how to do so. Any suggestions?

_Traceback (most recent call last):
  File "create_surrogate_data_STL.py", line 82, in <module>
    mask = Image.open(mask_path + '/' + str(label_ind).zfill(len(str(nb_classes)))[:-4] + '.png')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './surrogate_dataset/class_folder_16000_set/00000.png'_

**Comment by pratt3000** [comment]
Did you find the solution?? I am facing the same issue

**Comment by pratt3000** [comment]
`Traceback (most recent call last):
  File "create_surrogate_data_STL.py", line 77, in <module>
    mask = Image.open(mask_path + '/' + str(label_ind).zfill(len(str(nb_classes)))[:-4] + '_edge.png')
  File "/home/pratt3000/anaconda3/lib/python3.8/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './surrogate_dataset/class_folder_16000_set_edge/00_edge.png'`

**Comment by pratt3000** [comment]
Traceback (most recent call last):
  File "create_surrogate_data_STL.py", line 77, in <module>
    mask = Image.open(mask_path + '/' + str(label_ind).zfill(len(str(nb_classes)))[:-4] + '_edge.png')
  File "/home/pratt3000/anaconda3/lib/python3.8/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './surrogate_dataset/class_folder_16000_set_edge/00_edge.png'

**Comment by pratt3000** [comment]
'_edge' part was added in the later version maybe but the fundamental issue remains the same

**Comment by Mtorriente** [comment]
Good Morning, yes i found the solution and code runned perfectly.

You need to execute first this file to create the edges of the images:
https://github.com/EricArazo/ExemplarCNN/blob/master/surrogate_dataset/edges/0_compute_edge_masks.py

And as far as i remember, change the folder directory name so it matches the one in create_surrogate:
```

_> out_path = '../class_folder_edge_16000_imagenet/'
> class_folder_16000_set_edge/_

If you have any further questions, please let me know
```

**Comment by pratt3000** [comment]
Thank you for the quick reply! I was also stuck at the surrogate_dataset/splitting_data_small_val.py file. It wont run and gives an error at this line : 
`images = os.listdir('./data/' + class_i)`
The stl dataset has only binary files in it (and a few text files), I think the code expects the dataset to be in folders of images (folders of corresponding classes). How did you go about this?

**Comment by pratt3000** [comment]
Thank you for the quick reply! I was also stuck at the [https://github.com/EricArazo/ExemplarCNN/blob/master/surrogate_dataset/splitting_data_small_val.py](url) file. It wont run and gives an error at this line :
`images = os.listdir('./data/' + class_i)`
The stl dataset has only binary files in it (and a few text files), I think the code expects the dataset to be in folders of images (folders of corresponding classes). How did you go about this?

**Comment by Mtorriente** [comment]
Yes, modify in the create_surrogate file, line 74, the directory: 'data_35' into ' data'.
After that, run the split_data_small file.
It should work.

**Comment by pratt3000** [comment]
yup, everything it running smoothly now. Thank you!
