### ISSUE TITLE
No module named 'networks'

### ISSUE THREAD

**Issue by Mtorriente** [EricArazo/ExemplarCNN#2]
When i try to run training_scripts/exp083.py file appears this error:

Traceback (most recent call last):
  File "training_scripts/exp083.py", line 21, in <module>
    from networks import largest as Net
ModuleNotFoundError: No module named 'networks'

**Comment by EricArazo** [comment]
Apologies for the late reply. I just uploaded the missing file.
Thanks for reporting it!
